---
title: "foodwebs-eda"
author: "Misha Leong"
date: "1/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup environment

Load libraries and files to work with

```{r loadup}
# load libraries
library(tidyverse)
library(cooccur)

# load files
load('data/aoh.Rdata') # large 7roomsFamilies dataset from Bertone PeerJ paper
load('data/core.Rdata') # list of 47 core species from Leong Sci Reports paper

```

## Some basic stats

```{r basics, echo=FALSE}
head(aoh)
head(core)
aoh_core <- semi_join(aoh, core, by = "familyLong")
```


## Function to call cooccurrence
```{r coreFunction}
run_cooccur <- function (room_data, room) {
  # build a presence/absence matrix
  core_matrix <- room_data %>%
    group_by(roomUnique, familyLong) %>%
    summarise(obs = n()) %>%
    spread(familyLong, obs, fill = 0) %>%
    as.data.frame() 
  rownames(core_matrix) <-  core_matrix[,1]
  core_matrix <- core_matrix[, -1]
  core_matrix <- t(core_matrix) # transpose data frame
  
  # run cooccur program
  cooccur_room <- cooccur(mat = core_matrix, type = "spp_site", 
                          spp_names = TRUE, thresh = TRUE)
  
  return(cooccur_room)
}
```


```{r pos}
 # output the main relationships for each room
  # results table is filtered for significant pairwise observations where 
  # species are found occurring together greater than expected. For further 
  # explanation of results table see:
  # https://www.jstatsoft.org/article/view/v069c02/v69c02.pdf
pos <- function (cooccur_room) { 
  pos_pairs <- as.tibble(cooccur_room$results) %>% 
    arrange(p_gt) %>%
    filter(p_gt < 0.05) %>%
    mutate(room = i)%>%
    select (room, sp1_name, sp2_name, everything())
  return (pos_pairs)
}
  
```

```{r neg}
neg <- function (cooccur_room, i) { 
  neg_pairs <- as.tibble(cooccur_room$results) %>% 
    arrange(p_lt) %>%
    filter(p_lt < 0.05) %>%
    mutate(room = i) %>%
    select (room, sp1_name, sp2_name, everything())
  return (neg_pairs)
}
```


```{r}
# calling the above fuction
room_names <- c("basement", "bath", "bed", "common", "kitchen", "attic")

# create simple ranking tables for each taxa (landcover collapsed)
lapply(room_names, function(i){
  room_results <- assign(paste0("cooccur_", i), run_cooccur(aoh_core %>% filter (roomType == i), i), 
         envir = .GlobalEnv)
  summary(room_results)
  plot(room_results)
  assign(paste0("posPairs_", i) , pos(room_results, i), 
         envir = .GlobalEnv)
  assign(paste0("negPairs_", i) , neg(room_results, i), 
         envir = .GlobalEnv)
})

pos_rooms <- posPairs_basement %>%
  bind_rows(posPairs_bath, posPairs_bed, posPairs_common, posPairs_kitchen, 
            posPairs_attic)

neg_rooms <- negPairs_basement %>%
  bind_rows(negPairs_bath, negPairs_bed, negPairs_common, negPairs_kitchen, 
            negPairs_attic)
 
  
  
  
```


 Compare to cooccur
```{r}
#now run coccurrence!
library(cooccur)
setwd("~/Dropbox/AoH/dataMain/Useful")
aoh<-read.csv("cooccurPAgreaterThan10.csv")
cooccur.aoh<-cooccur(mat=aoh, type="site_spp", spp_names=TRUE, thresh=TRUE)
summary(cooccur.aoh)
plot(cooccur.aoh)
es<-effect.sizes(cooccur.aoh, standardized=TRUE,matrix=FALSE)
scuti<-pair(cooccur.aoh, "Scutigeromorpha..house.centipedes._Scutigeridae..house.centipedes.", all=FALSE)
scutiALL<-pair(cooccur.aoh, "Scutigeromorpha..house.centipedes._Scutigeridae..house.centipedes.", all=TRUE)
pair.profile(cooccur.aoh)
co<-pair.attributes(cooccur.aoh)
print(cooccur.aoh)
prob.table(cooccur.aoh)


zygen<-pair(cooccur.aoh, "Zygentoma..silverfish._Lepismatidae..silverfish.", all=FALSE)
zygenALL<-pair(cooccur.aoh, "Zygentoma..silverfish._Lepismatidae..silverfish.", all=TRUE)

write.csv(es, "es.csv")
write.csv(scuti, "scuti.csv")
write.csv(scutiALL, "scutiALL.csv")
write.csv(zygen, "zygen.csv")
write.csv(zygenALL, "zygenALL.csv")

data(finches)
cooccur.finches <- cooccur(mat=finches,
                           type="spp_site",
                           thresh=FALSE,
                           spp_names=TRUE)
effect.sizes(cooccur.finches,matrix=TRUE)




for(i in 1:10) {
  if(i %% 2 == 0)
    print(paste(i, "is even"))
}

```
 

```{r rooms}


  
```
